{% set version = "1.44.0" %}

package:
  name: nvidia-dali-python
  version: {{ version }}

source:
  - url: https://github.com/NVIDIA/DALI/archive/refs/tags/v{{ version }}.tar.gz
    sha256: f6ad0d91f0eaf52a8e556124edae0e73774d77b304ac339c7ecd684267e0a0dc
    patches:
      - use_shared_deps.diff
      - fix_nvimgcodec.diff

  - url: https://github.com/cocodataset/cocoapi/archive/8c9bcc3cf640524c4c20a9c40e89cb6a2f2fa0e9.tar.gz
    sha256: 4dd3450bab2287d1c1b271cf4a1420db05294194f0ad9af4e3af592d6f2b4410
    folder: third_party/cocoapi

build:
  number: 2
  # skip: true  # [py!=312]
  skip: true  # [not linux64 or cuda_compiler_version == "None"]
  ignore_run_exports_from:
    - {{ compiler('cuda') }}
    - cudatoolkit       # [(cuda_compiler_version or "").startswith("11")]
    - libcufft-dev      # [(cuda_compiler_version or "").startswith("12")]
    - libnpp-dev        # [(cuda_compiler_version or "").startswith("12")]
    - cuda-cudart-dev   # [(cuda_compiler_version or "").startswith("12")]
    - libnvjpeg-dev     # [(cuda_compiler_version or "").startswith("12")]
    - libcurand-dev     # [(cuda_compiler_version or "").startswith("12")]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - {{ stdlib('c') }}
    - cmake
    - ninja
  host:
    - python
    - pip
    - setuptools
    - pybind11
    - cfitsio
    - libjpeg-turbo
    - libtiff
    - python-clang
    - libboost-headers
    - protobuf
    - libprotobuf
    - dlpack
    - rapidjson
    - libopencv
    - cutlass
    - libabseil
    - cuda-version {{ cuda_compiler_version }}
    - cudatoolkit       # [(cuda_compiler_version or "").startswith("11")]
    - libcufft-dev      # [(cuda_compiler_version or "").startswith("12")]
    - libnpp-dev        # [(cuda_compiler_version or "").startswith("12")]
    - cuda-cudart-dev   # [(cuda_compiler_version or "").startswith("12")]
    - libnvjpeg-dev     # [(cuda_compiler_version or "").startswith("12")]
    - libcurand-dev     # [(cuda_compiler_version or "").startswith("12")]
    - cuda-nvml-dev     # [(cuda_compiler_version or "").startswith("12")]
  run:
    - python
    # https://github.com/NVIDIA/DALI/blob/main/dali/python/setup.py.in
    - astunparse >=1.6.0,<=1.6.3
    - gast >=0.3.3,<=0.6.0
    - six >=1.16,<=1.16
    - dm-tree <=0.1.8
    - packaging <=24.2
    - {{ pin_compatible('cuda-version', min_pin='x', max_pin='x') }}
    - cudatoolkit   # [(cuda_compiler_version or "").startswith("11")]
    - libcufft      # [(cuda_compiler_version or "").startswith("12")]
    - libnpp        # [(cuda_compiler_version or "").startswith("12")]
    - cuda-cudart   # [(cuda_compiler_version or "").startswith("12")]
    - libnvjpeg     # [(cuda_compiler_version or "").startswith("12")]
  run_constrained:
    # https://github.com/NVIDIA/DALI/tree/v1.44.0/third_party
    - libboost-headers 1.85
test:
  imports:
    - nvidia.dali
  commands:
    - pip check
    # rec2idx requires mxnet which is not available on the channel as of 2025.1.9
    # - rec2idx --help
    - tfrecord2idx --help
    - wds2idx --help
  requires:
    - pip

about:
  home: https://github.com/NVIDIA/dali
  summary: A GPU-accelerated library for data loading and pre-processing to accelerate deep learning applications.
  description: |
    A GPU-accelerated library containing highly optimized building blocks and
    an execution engine for data processing to accelerate deep learning training
    and inference applications.
  license: Apache-2.0
  license_file:
    - LICENSE
    - COPYRIGHT
    - third_party/README.rst

extra:
  recipe-maintainers:
    - conda-forge/cuda
    - isuruf
    - timkpaine
