{% set version = "1.40.0" %}

package:
  name: nvidia-dali-python
  version: {{ version }}

source:
  - url: https://github.com/NVIDIA/DALI/archive/refs/tags/v{{ version }}.tar.gz
    sha256: eb860a930ab450a23ed72f45c03f56bee8eb02d20d10269e9dcea9f3d1f4043e
    patches:
      - use_shared_deps.diff
      - fix_nvimgcodec.diff

  - url: https://github.com/cocodataset/cocoapi/archive/8c9bcc3cf640524c4c20a9c40e89cb6a2f2fa0e9.tar.gz
    sha256: 4dd3450bab2287d1c1b271cf4a1420db05294194f0ad9af4e3af592d6f2b4410
    folder: third_party/cocoapi

build:
  number: 0
  skip: True   # [not linux64 or cuda_compiler_version == "None"]
  # TODO: takes too long to build all python variants on staged-recipes
  # remove in feedstock
  skip: True   # [py != 39]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - {{ stdlib('c') }}
    - cmake
    - make
  host:
    - python
    - pip
    - setuptools
    - pybind11
    - cfitsio
    - libjpeg-turbo
    - libtiff
    - python-clang
    - libboost-devel
    - protobuf
    - libprotobuf
    - dlpack
    - rapidjson
    - libopencv
    - cutlass
    - libabseil
    - cuda-nvtx-dev     # [(cuda_compiler_version or "").startswith("12")]
    - libcufft-dev      # [(cuda_compiler_version or "").startswith("12")]
    - libnpp-dev        # [(cuda_compiler_version or "").startswith("12")]
    - cuda-cudart-dev 12.0.*   # [(cuda_compiler_version or "").startswith("12")]
    - libnvjpeg-dev     # [(cuda_compiler_version or "").startswith("12")]
    - libcurand-dev     # [(cuda_compiler_version or "").startswith("12")]
    - cuda-nvml-dev     # [(cuda_compiler_version or "").startswith("12")]
  run:
    - python
    - astunparse >=1.6.0
    - gast >=0.3.3
    - dm-tree

test:
  imports:
    - nvidia.dali
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/NVIDIA/dali
  summary: A GPU-accelerated library for data loading and pre-processing to accelerate deep learning applications.
  description: |
    A GPU-accelerated library containing highly optimized building blocks and
    an execution engine for data processing to accelerate deep learning training
    and inference applications.
  license: Apache-2.0
  license_file:
    - LICENSE
    - COPYRIGHT
    - third_party/README.rst

extra:
  recipe-maintainers:
    - isuruf
    - timkpaine
