# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: linux
  pool:
    vmImage: ubuntu-latest
  strategy:
    matrix:
      linux_64_c_stdlib_version2.17cuda_compiler_version12.9python3.10.____cpython:
        CONFIG: linux_64_c_stdlib_version2.17cuda_compiler_version12.9python3.10.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
        SHORT_CONFIG: linux_64_c_stdlib_version2.17cuda_compil_h4300bc21
      linux_64_c_stdlib_version2.17cuda_compiler_version12.9python3.11.____cpython:
        CONFIG: linux_64_c_stdlib_version2.17cuda_compiler_version12.9python3.11.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
        SHORT_CONFIG: linux_64_c_stdlib_version2.17cuda_compil_h3747ab2d
      linux_64_c_stdlib_version2.17cuda_compiler_version12.9python3.12.____cpython:
        CONFIG: linux_64_c_stdlib_version2.17cuda_compiler_version12.9python3.12.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
        SHORT_CONFIG: linux_64_c_stdlib_version2.17cuda_compil_h86c3c167
      linux_64_c_stdlib_version2.17cuda_compiler_version12.9python3.13.____cp313:
        CONFIG: linux_64_c_stdlib_version2.17cuda_compiler_version12.9python3.13.____cp313
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
        SHORT_CONFIG: linux_64_c_stdlib_version2.17cuda_compil_h88f978e6
      linux_64_c_stdlib_version2.28cuda_compiler_version13.0python3.10.____cpython:
        CONFIG: linux_64_c_stdlib_version2.28cuda_compiler_version13.0python3.10.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
        SHORT_CONFIG: linux_64_c_stdlib_version2.28cuda_compil_h7bc1faf3
      linux_64_c_stdlib_version2.28cuda_compiler_version13.0python3.11.____cpython:
        CONFIG: linux_64_c_stdlib_version2.28cuda_compiler_version13.0python3.11.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
        SHORT_CONFIG: linux_64_c_stdlib_version2.28cuda_compil_h9cd8e738
      linux_64_c_stdlib_version2.28cuda_compiler_version13.0python3.12.____cpython:
        CONFIG: linux_64_c_stdlib_version2.28cuda_compiler_version13.0python3.12.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
        SHORT_CONFIG: linux_64_c_stdlib_version2.28cuda_compil_h8d03b736
      linux_64_c_stdlib_version2.28cuda_compiler_version13.0python3.13.____cp313:
        CONFIG: linux_64_c_stdlib_version2.28cuda_compiler_version13.0python3.13.____cp313
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
        SHORT_CONFIG: linux_64_c_stdlib_version2.28cuda_compil_h7b65d883
      linux_aarch64_c_stdlib_version2.17cuda_compiler_version12.9python3.10.____cpython:
        CONFIG: linux_aarch64_c_stdlib_version2.17cuda_compiler_version12.9python3.10.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
        SHORT_CONFIG: linux_aarch64_c_stdlib_version2.17cuda_c_h36fe1278
      linux_aarch64_c_stdlib_version2.17cuda_compiler_version12.9python3.11.____cpython:
        CONFIG: linux_aarch64_c_stdlib_version2.17cuda_compiler_version12.9python3.11.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
        SHORT_CONFIG: linux_aarch64_c_stdlib_version2.17cuda_c_h96f5decc
      linux_aarch64_c_stdlib_version2.17cuda_compiler_version12.9python3.12.____cpython:
        CONFIG: linux_aarch64_c_stdlib_version2.17cuda_compiler_version12.9python3.12.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
        SHORT_CONFIG: linux_aarch64_c_stdlib_version2.17cuda_c_ha298f0b8
      linux_aarch64_c_stdlib_version2.17cuda_compiler_version12.9python3.13.____cp313:
        CONFIG: linux_aarch64_c_stdlib_version2.17cuda_compiler_version12.9python3.13.____cp313
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
        SHORT_CONFIG: linux_aarch64_c_stdlib_version2.17cuda_c_h22590c6c
      linux_aarch64_c_stdlib_version2.28cuda_compiler_version13.0python3.10.____cpython:
        CONFIG: linux_aarch64_c_stdlib_version2.28cuda_compiler_version13.0python3.10.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
        SHORT_CONFIG: linux_aarch64_c_stdlib_version2.28cuda_c_h70ef84ec
      linux_aarch64_c_stdlib_version2.28cuda_compiler_version13.0python3.11.____cpython:
        CONFIG: linux_aarch64_c_stdlib_version2.28cuda_compiler_version13.0python3.11.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
        SHORT_CONFIG: linux_aarch64_c_stdlib_version2.28cuda_c_he30e760b
      linux_aarch64_c_stdlib_version2.28cuda_compiler_version13.0python3.12.____cpython:
        CONFIG: linux_aarch64_c_stdlib_version2.28cuda_compiler_version13.0python3.12.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
        SHORT_CONFIG: linux_aarch64_c_stdlib_version2.28cuda_c_ha6a8df05
      linux_aarch64_c_stdlib_version2.28cuda_compiler_version13.0python3.13.____cp313:
        CONFIG: linux_aarch64_c_stdlib_version2.28cuda_compiler_version13.0python3.13.____cp313
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
        SHORT_CONFIG: linux_aarch64_c_stdlib_version2.28cuda_c_h69c78151
  timeoutInMinutes: 360
  variables: {}

  steps:
  - script: |
         sudo mkdir -p /opt/empty_dir || true
         for d in \
                  /opt/ghc \
                  /opt/hostedtoolcache \
                  /usr/lib/jvm \
                  /usr/local/.ghcup \
                  /usr/local/lib/android \
                  /usr/local/share/powershell \
                  /usr/share/dotnet \
                  /usr/share/swift \
                  ; do
           sudo rsync --stats -a --delete /opt/empty_dir/ $d || true
         done
         sudo apt-get purge -y -f firefox \
                                  google-chrome-stable \
                                  microsoft-edge-stable
         sudo apt-get autoremove -y >& /dev/null
         sudo apt-get autoclean -y >& /dev/null
         df -h
    displayName: Manage disk space
  # configure qemu binfmt-misc running.  This allows us to run docker containers
  # embedded qemu-static
  - script: |
      docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
      ls /proc/sys/fs/binfmt_misc/
    condition: not(startsWith(variables['CONFIG'], 'linux_64'))
    displayName: Configure binfmt_misc

  - script: |
        export CI=azure
        export flow_run_id=azure_$(Build.BuildNumber).$(System.JobAttempt)
        export remote_url=$(Build.Repository.Uri)
        export sha=$(Build.SourceVersion)
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        if [[ "${BUILD_REASON:-}" == "PullRequest" ]]; then
          export IS_PR_BUILD="True"
        else
          export IS_PR_BUILD="False"
        fi
        .scripts/run_docker_build.sh
    displayName: Run docker build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)
      FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
      STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)
  - script: |
        export CI=azure
        export CI_RUN_ID=$(build.BuildNumber).$(system.JobAttempt)
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        export CONDA_BLD_DIR=build_artifacts
        export ARTIFACT_STAGING_DIR="$(Build.ArtifactStagingDirectory)"
        # Archive everything in CONDA_BLD_DIR except environments
        export BLD_ARTIFACT_PREFIX=conda_artifacts
        if [[ "$AGENT_JOBSTATUS" == "Failed" ]]; then
          # Archive the CONDA_BLD_DIR environments only when the job fails
          export ENV_ARTIFACT_PREFIX=conda_envs
        fi
        ./.scripts/create_conda_build_artifacts.sh
    displayName: Prepare conda build artifacts
    condition: succeededOrFailed()

  - task: PublishPipelineArtifact@1
    displayName: Store conda build artifacts
    condition: not(eq(variables.BLD_ARTIFACT_PATH, ''))
    inputs:
      targetPath: $(BLD_ARTIFACT_PATH)
      artifactName: $(BLD_ARTIFACT_NAME)

  - task: PublishPipelineArtifact@1
    displayName: Store conda build environment artifacts
    condition: not(eq(variables.ENV_ARTIFACT_PATH, ''))
    inputs:
      targetPath: $(ENV_ARTIFACT_PATH)
      artifactName: $(ENV_ARTIFACT_NAME)
